#!/bin/sh

# exit on error
set -e
# turn on command echoing
set -v

# The data should have already been generated by ./1_run.sh

/data/keeling/a/yicenl2/d/project_camp/partmc/build/urban_plume_process
